Removed closing "controller" and replaced it with crazyswarm magic
utiasDSL/lsy_drone_racing pull request #23
Opened 2024-12-24 20:13 UTC by j-kelm

Merry Christmas, everyone! Rejoice, Santa has finally brought a working™ closing "controller" so that the amount of innocent drone casualties may be reduced in the upcoming year.

Since it uses crazyswarm directly, it is incompatible with the existing closing controller architecture. Thus, my changes include fully removing the last iteration of the closing controller.

Thoroughly tested on hardware for varying speeds and race tracks. A little hacky, but works. Also fixes #22.

2024-12-31 16:05 UTC, amacati requested changes
Looks good. Can you address the minor comments I had? Then we can merge and save a few drone markers from a premature demise.

2024-12-31 16:05 UTC, amacati commented on lsy_drone_racing/envs/drone_racing_deploy_env.py
> +        except Exception as e:
Do you need the general Exception catch here? If so, why?

2024-12-31 16:05 UTC, amacati commented on lsy_drone_racing/envs/drone_racing_deploy_env.py
> +            time.sleep(BREAKING_DURATION - 1)
```suggestion
            time.sleep(BREAKING_DURATION - 1)  # Smoothly transition to next position by setting the next goal earlier
```

2025-01-04 14:08 UTC, j-kelm commented on lsy_drone_racing/envs/drone_racing_deploy_env.py
> +        except Exception as e:
The general Exception catch is not necessary and admittedly bad code. At least notifysetpointstop and maybe also the other calls to cf may raise a rospy.service.ServiceException if the drone is not reachable (e.g. because of an emergency shutoff of the drone), resulting in hanging code in my case.

Catching the rospy.service.ServiceException should probably be enough, but I cannot validate this on the drone anymore.

2025-01-06 18:11 UTC, merged